[colors]
[colors.primary]
# background = "#000000"
background = "#040404"
foreground = "#e3e8ea"

[colors.normal]
black =  "#1C1C1C"
red =    "#AF5F5F"
green =  "#87AF87"
yellow = "#d9d996"
blue =   "#5F87AF"
magenta ="#5F5F87"
cyan =    "#5F8787"
white =   "#e3e8ea"

[colors.bright]
black =   "#444444"
red=     "#FC5F5A"
green=   "#87AF87"
yellow=  "#FFFFAF"
blue=    "#8FAFD7"
magenta= "#8787AF"
cyan=    "#5FAFAF"
white=   "#FFFFFF"

[window]
# padding = { x = 10, y = 8 }
# opacity = 0.80

padding = { x = 35, y = 35 }
opacity = 1

[scrolling]
history = 50000
multiplier = 3

[font]
normal = { family = "SauceCodePro Nerd Font", style = "Regular" }
bold = { family = "SauceCodePro Nerd Font", style = "Bold" }
italic = { family = "SauceCodePro Nerd Font", style = "Italic" }
bold_italic = { family = "SauceCodePro Nerd Font", style = "Bold Italic" }

size = 18.0

